/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRedeemOrderRevert,
  IRedeemOrderRevertInterface,
} from "../IRedeemOrderRevert";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "encodedWormholeMessage",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "circleBridgeMessage",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "circleAttestation",
            type: "bytes",
          },
        ],
        internalType: "struct OrderResponse",
        name: "response",
        type: "tuple",
      },
    ],
    name: "redeemOrderRevert",
    outputs: [
      {
        internalType: "enum RevertType",
        name: "",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRedeemOrderRevert__factory {
  static readonly abi = _abi;
  static createInterface(): IRedeemOrderRevertInterface {
    return new utils.Interface(_abi) as IRedeemOrderRevertInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRedeemOrderRevert {
    return new Contract(address, _abi, signerOrProvider) as IRedeemOrderRevert;
  }
}
