/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { ITokenMinter, ITokenMinterInterface } from "../ITokenMinter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "burnLimitsPerMessage",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sourceIdHash",
        type: "bytes32",
      },
    ],
    name: "remoteTokensToLocalTokens",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITokenMinter__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenMinterInterface {
    return new utils.Interface(_abi) as ITokenMinterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenMinter {
    return new Contract(address, _abi, signerOrProvider) as ITokenMinter;
  }
}
