/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ICircleIntegration {
  export type DepositWithPayloadStruct = {
    token: PromiseOrValue<BytesLike>;
    amount: PromiseOrValue<BigNumberish>;
    sourceDomain: PromiseOrValue<BigNumberish>;
    targetDomain: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    fromAddress: PromiseOrValue<BytesLike>;
    mintRecipient: PromiseOrValue<BytesLike>;
    payload: PromiseOrValue<BytesLike>;
  };

  export type DepositWithPayloadStructOutput = [
    string,
    BigNumber,
    number,
    number,
    BigNumber,
    string,
    string,
    string
  ] & {
    token: string;
    amount: BigNumber;
    sourceDomain: number;
    targetDomain: number;
    nonce: BigNumber;
    fromAddress: string;
    mintRecipient: string;
    payload: string;
  };

  export type RedeemParametersStruct = {
    encodedWormholeMessage: PromiseOrValue<BytesLike>;
    circleBridgeMessage: PromiseOrValue<BytesLike>;
    circleAttestation: PromiseOrValue<BytesLike>;
  };

  export type RedeemParametersStructOutput = [string, string, string] & {
    encodedWormholeMessage: string;
    circleBridgeMessage: string;
    circleAttestation: string;
  };

  export type TransferParametersStruct = {
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    targetChain: PromiseOrValue<BigNumberish>;
    mintRecipient: PromiseOrValue<BytesLike>;
  };

  export type TransferParametersStructOutput = [
    string,
    BigNumber,
    number,
    string
  ] & {
    token: string;
    amount: BigNumber;
    targetChain: number;
    mintRecipient: string;
  };
}

export interface ICircleIntegrationInterface extends utils.Interface {
  functions: {
    "chainId()": FunctionFragment;
    "circleBridge()": FunctionFragment;
    "circleTokenMinter()": FunctionFragment;
    "circleTransmitter()": FunctionFragment;
    "decodeDepositWithPayload(bytes)": FunctionFragment;
    "encodeDepositWithPayload((bytes32,uint256,uint32,uint32,uint64,bytes32,bytes32,bytes))": FunctionFragment;
    "evmChain()": FunctionFragment;
    "fetchLocalTokenAddress(uint32,bytes32)": FunctionFragment;
    "getChainIdFromDomain(uint32)": FunctionFragment;
    "getDomainFromChainId(uint16)": FunctionFragment;
    "getRegisteredEmitter(uint16)": FunctionFragment;
    "isAcceptedToken(address)": FunctionFragment;
    "isInitialized(address)": FunctionFragment;
    "isMessageConsumed(bytes32)": FunctionFragment;
    "localDomain()": FunctionFragment;
    "redeemTokensWithPayload((bytes,bytes,bytes))": FunctionFragment;
    "registerEmitterAndDomain(bytes)": FunctionFragment;
    "transferTokensWithPayload((address,uint256,uint16,bytes32),uint32,bytes)": FunctionFragment;
    "updateWormholeFinality(bytes)": FunctionFragment;
    "upgradeContract(bytes)": FunctionFragment;
    "verifyGovernanceMessage(bytes,uint8)": FunctionFragment;
    "wormhole()": FunctionFragment;
    "wormholeFinality()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "chainId"
      | "circleBridge"
      | "circleTokenMinter"
      | "circleTransmitter"
      | "decodeDepositWithPayload"
      | "encodeDepositWithPayload"
      | "evmChain"
      | "fetchLocalTokenAddress"
      | "getChainIdFromDomain"
      | "getDomainFromChainId"
      | "getRegisteredEmitter"
      | "isAcceptedToken"
      | "isInitialized"
      | "isMessageConsumed"
      | "localDomain"
      | "redeemTokensWithPayload"
      | "registerEmitterAndDomain"
      | "transferTokensWithPayload"
      | "updateWormholeFinality"
      | "upgradeContract"
      | "verifyGovernanceMessage"
      | "wormhole"
      | "wormholeFinality"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "circleBridge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circleTokenMinter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "circleTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decodeDepositWithPayload",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeDepositWithPayload",
    values: [ICircleIntegration.DepositWithPayloadStruct]
  ): string;
  encodeFunctionData(functionFragment: "evmChain", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fetchLocalTokenAddress",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainIdFromDomain",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainFromChainId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegisteredEmitter",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isAcceptedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isMessageConsumed",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemTokensWithPayload",
    values: [ICircleIntegration.RedeemParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEmitterAndDomain",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTokensWithPayload",
    values: [
      ICircleIntegration.TransferParametersStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWormholeFinality",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeContract",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyGovernanceMessage",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "wormhole", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "wormholeFinality",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "circleBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "circleTokenMinter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "circleTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeDepositWithPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeDepositWithPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "evmChain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fetchLocalTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChainIdFromDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainFromChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegisteredEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAcceptedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isMessageConsumed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redeemTokensWithPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerEmitterAndDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTokensWithPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWormholeFinality",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyGovernanceMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wormhole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wormholeFinality",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ICircleIntegration extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICircleIntegrationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    chainId(overrides?: CallOverrides): Promise<[number]>;

    circleBridge(overrides?: CallOverrides): Promise<[string]>;

    circleTokenMinter(overrides?: CallOverrides): Promise<[string]>;

    circleTransmitter(overrides?: CallOverrides): Promise<[string]>;

    decodeDepositWithPayload(
      encoded: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [ICircleIntegration.DepositWithPayloadStructOutput] & {
        message: ICircleIntegration.DepositWithPayloadStructOutput;
      }
    >;

    encodeDepositWithPayload(
      message: ICircleIntegration.DepositWithPayloadStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    evmChain(overrides?: CallOverrides): Promise<[BigNumber]>;

    fetchLocalTokenAddress(
      sourceDomain: PromiseOrValue<BigNumberish>,
      sourceToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getChainIdFromDomain(
      domain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getDomainFromChainId(
      chainId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getRegisteredEmitter(
      emitterChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isAcceptedToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isMessageConsumed(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    localDomain(overrides?: CallOverrides): Promise<[number]>;

    redeemTokensWithPayload(
      params: ICircleIntegration.RedeemParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerEmitterAndDomain(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferTokensWithPayload(
      transferParams: ICircleIntegration.TransferParametersStruct,
      batchId: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateWormholeFinality(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeContract(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyGovernanceMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      action: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { messageHash: string; payload: string }>;

    wormhole(overrides?: CallOverrides): Promise<[string]>;

    wormholeFinality(overrides?: CallOverrides): Promise<[number]>;
  };

  chainId(overrides?: CallOverrides): Promise<number>;

  circleBridge(overrides?: CallOverrides): Promise<string>;

  circleTokenMinter(overrides?: CallOverrides): Promise<string>;

  circleTransmitter(overrides?: CallOverrides): Promise<string>;

  decodeDepositWithPayload(
    encoded: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<ICircleIntegration.DepositWithPayloadStructOutput>;

  encodeDepositWithPayload(
    message: ICircleIntegration.DepositWithPayloadStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  evmChain(overrides?: CallOverrides): Promise<BigNumber>;

  fetchLocalTokenAddress(
    sourceDomain: PromiseOrValue<BigNumberish>,
    sourceToken: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getChainIdFromDomain(
    domain: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  getDomainFromChainId(
    chainId_: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  getRegisteredEmitter(
    emitterChainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  isAcceptedToken(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isInitialized(
    impl: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isMessageConsumed(
    hash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  localDomain(overrides?: CallOverrides): Promise<number>;

  redeemTokensWithPayload(
    params: ICircleIntegration.RedeemParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerEmitterAndDomain(
    encodedMessage: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferTokensWithPayload(
    transferParams: ICircleIntegration.TransferParametersStruct,
    batchId: PromiseOrValue<BigNumberish>,
    payload: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateWormholeFinality(
    encodedMessage: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeContract(
    encodedMessage: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyGovernanceMessage(
    encodedMessage: PromiseOrValue<BytesLike>,
    action: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { messageHash: string; payload: string }>;

  wormhole(overrides?: CallOverrides): Promise<string>;

  wormholeFinality(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    chainId(overrides?: CallOverrides): Promise<number>;

    circleBridge(overrides?: CallOverrides): Promise<string>;

    circleTokenMinter(overrides?: CallOverrides): Promise<string>;

    circleTransmitter(overrides?: CallOverrides): Promise<string>;

    decodeDepositWithPayload(
      encoded: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<ICircleIntegration.DepositWithPayloadStructOutput>;

    encodeDepositWithPayload(
      message: ICircleIntegration.DepositWithPayloadStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    evmChain(overrides?: CallOverrides): Promise<BigNumber>;

    fetchLocalTokenAddress(
      sourceDomain: PromiseOrValue<BigNumberish>,
      sourceToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getChainIdFromDomain(
      domain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    getDomainFromChainId(
      chainId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    getRegisteredEmitter(
      emitterChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    isAcceptedToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isMessageConsumed(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    localDomain(overrides?: CallOverrides): Promise<number>;

    redeemTokensWithPayload(
      params: ICircleIntegration.RedeemParametersStruct,
      overrides?: CallOverrides
    ): Promise<ICircleIntegration.DepositWithPayloadStructOutput>;

    registerEmitterAndDomain(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferTokensWithPayload(
      transferParams: ICircleIntegration.TransferParametersStruct,
      batchId: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateWormholeFinality(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeContract(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyGovernanceMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      action: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { messageHash: string; payload: string }>;

    wormhole(overrides?: CallOverrides): Promise<string>;

    wormholeFinality(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    circleBridge(overrides?: CallOverrides): Promise<BigNumber>;

    circleTokenMinter(overrides?: CallOverrides): Promise<BigNumber>;

    circleTransmitter(overrides?: CallOverrides): Promise<BigNumber>;

    decodeDepositWithPayload(
      encoded: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeDepositWithPayload(
      message: ICircleIntegration.DepositWithPayloadStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    evmChain(overrides?: CallOverrides): Promise<BigNumber>;

    fetchLocalTokenAddress(
      sourceDomain: PromiseOrValue<BigNumberish>,
      sourceToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChainIdFromDomain(
      domain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDomainFromChainId(
      chainId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRegisteredEmitter(
      emitterChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAcceptedToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isMessageConsumed(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    localDomain(overrides?: CallOverrides): Promise<BigNumber>;

    redeemTokensWithPayload(
      params: ICircleIntegration.RedeemParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerEmitterAndDomain(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferTokensWithPayload(
      transferParams: ICircleIntegration.TransferParametersStruct,
      batchId: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateWormholeFinality(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeContract(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyGovernanceMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      action: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    wormhole(overrides?: CallOverrides): Promise<BigNumber>;

    wormholeFinality(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    chainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    circleBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    circleTokenMinter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    circleTransmitter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    decodeDepositWithPayload(
      encoded: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeDepositWithPayload(
      message: ICircleIntegration.DepositWithPayloadStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    evmChain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fetchLocalTokenAddress(
      sourceDomain: PromiseOrValue<BigNumberish>,
      sourceToken: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainIdFromDomain(
      domain: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDomainFromChainId(
      chainId_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRegisteredEmitter(
      emitterChainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAcceptedToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isInitialized(
      impl: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isMessageConsumed(
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    localDomain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeemTokensWithPayload(
      params: ICircleIntegration.RedeemParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerEmitterAndDomain(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferTokensWithPayload(
      transferParams: ICircleIntegration.TransferParametersStruct,
      batchId: PromiseOrValue<BigNumberish>,
      payload: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateWormholeFinality(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeContract(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyGovernanceMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      action: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    wormhole(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wormholeFinality(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
