/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type OrderResponseStruct = {
  encodedWormholeMessage: PromiseOrValue<BytesLike>;
  circleBridgeMessage: PromiseOrValue<BytesLike>;
  circleAttestation: PromiseOrValue<BytesLike>;
};

export type OrderResponseStructOutput = [string, string, string] & {
  encodedWormholeMessage: string;
  circleBridgeMessage: string;
  circleAttestation: string;
};

export type RedeemedFillStruct = {
  sender: PromiseOrValue<BytesLike>;
  senderChain: PromiseOrValue<BigNumberish>;
  token: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
  message: PromiseOrValue<BytesLike>;
};

export type RedeemedFillStructOutput = [
  string,
  number,
  string,
  BigNumber,
  string
] & {
  sender: string;
  senderChain: number;
  token: string;
  amount: BigNumber;
  message: string;
};

export interface IRedeemFillInterface extends utils.Interface {
  functions: {
    "redeemFill((bytes,bytes,bytes))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "redeemFill"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "redeemFill",
    values: [OrderResponseStruct]
  ): string;

  decodeFunctionResult(functionFragment: "redeemFill", data: BytesLike): Result;

  events: {};
}

export interface IRedeemFill extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRedeemFillInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    redeemFill(
      response: OrderResponseStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  redeemFill(
    response: OrderResponseStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    redeemFill(
      response: OrderResponseStruct,
      overrides?: CallOverrides
    ): Promise<RedeemedFillStructOutput>;
  };

  filters: {};

  estimateGas: {
    redeemFill(
      response: OrderResponseStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    redeemFill(
      response: OrderResponseStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
