/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type OrderResponseStruct = {
  encodedWormholeMessage: PromiseOrValue<BytesLike>;
  circleBridgeMessage: PromiseOrValue<BytesLike>;
  circleAttestation: PromiseOrValue<BytesLike>;
};

export type OrderResponseStructOutput = [string, string, string] & {
  encodedWormholeMessage: string;
  circleBridgeMessage: string;
  circleAttestation: string;
};

export interface IRedeemOrderRevertInterface extends utils.Interface {
  functions: {
    "redeemOrderRevert((bytes,bytes,bytes))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "redeemOrderRevert"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "redeemOrderRevert",
    values: [OrderResponseStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "redeemOrderRevert",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRedeemOrderRevert extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRedeemOrderRevertInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    redeemOrderRevert(
      response: OrderResponseStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  redeemOrderRevert(
    response: OrderResponseStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    redeemOrderRevert(
      response: OrderResponseStruct,
      overrides?: CallOverrides
    ): Promise<[number, string]>;
  };

  filters: {};

  estimateGas: {
    redeemOrderRevert(
      response: OrderResponseStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    redeemOrderRevert(
      response: OrderResponseStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
